# Generated by Django 5.0 on 2024-01-31 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_rename_productid_addcart_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='total_price',
        ),
    ]
